import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Header from "@/widgets/header";
import ThemeProviderWrapper from "@/shared/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="ru"
      className="dark"
      style={{ colorScheme: "dark" }}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased flex flex-col gap-4`}
      >
        <ThemeProviderWrapper>
          <Header />
          <main className="flex flex-1 sm:p-2 relative">
            <ToastContainer
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
            />
            <div className="main__wrapper flex-1 w-full max-w-[1400px] p-2 py-4 mx-auto rounded">
              {children}
            </div>
          </main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
